version: "3.9"
services:
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ttps
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
